pipeline:
  tests:
    image: python:3.6
    environment:
      - POSTGRES_USER=timeallot
      - DATABASE=postgres
    commands:
      - sleep 5
    when:
      event: [push]

  ssh:
    image: appleboy/drone-ssh
    host: timeallot.me
    username: sigrid
    secrets: [ ssh_key ]
    port: 22
    script:
      - echo hello
      - echo world


services:
  postgres:
    image: postgres:9.5
    environment:
      - POSTGRES_USER=timeallot