pipeline:

  tests:
    image: timeallot/testbase-tox
    when:
      event: push
    environment:
      - LANG=C.UTF-8
      - DATABASE=postgres
    group: testing
    commands:
      - tox -e tests

  isort:
    image: timeallot/testbase-tox
    when:
      event: push
    environment:
      - LANG=C.UTF-8
    group: testing
    commands:
      - tox -e isort

  flake8:
    image: timeallot/testbase-tox
    when:
      event: push
    environment:
      - LANG=C.UTF-8
    group: testing
    commands:
      - tox -e flake8

  yapf:
    image: timeallot/testbase-tox
    when:
      event: push
    environment:
      - LANG=C.UTF-8
    group: testing
    commands:
      - tox -e yapf

  coverage:
    image: timeallot/testbase-tox
    when:
      event: push
    environment:
      - LANG=C.UTF-8
    group: result
    commands:
      - tox -e coverage

  ssh:
    image: appleboy/drone-ssh
    host: timeallot.me
    secrets: [ ssh_username, ssh_key ]
    port: 22
    when:
      event: push
      branch: prod
    command_timeout: 600
    group: result
    script:
      - cd sites/timeallot-staging/
      - git stash && git fetch && git reset origin/prod --hard && docker-compose up -d --build --force-recreate && exit

services:
  postgres:
    image: postgres:9.5
    environment:
      - POSTGRES_USER=timeallot