pipeline:
  ssh:
    image: appleboy/drone-ssh
    host: timeallot.me
    secrets: [ ssh_username, ssh_key ]
    port: 22
    when:
      event: push
    command_timeout: 600
    script:
      - cd sites/timeallot-staging/
      - git fetch && git reset origin/master --hard && docker-compose build && docker container stop timeallotstaging_website_1  && docker-compose up -d --force-recreate && docker exec -it timeallotstaging_website_1 bash &&  python manage.py collectstatic --no-input && exit && exit
services:
  postgres:
    image: postgres:9.5
    environment:
      - POSTGRES_USER=timeallot