pipeline:
  tests:
    image: python:3.6
    environment:
      - POSTGRES_USER=timeallot
    secrets: [ default_from_email, server_email ]
    commands:
      - sleep 5
      - pip3 install -r requirements/development.txt
      - ./manage.py test
    when:
      event: [push]


services:
  postgres:
    image: postgres:9.5
    environment:
      - POSTGRES_USER=timeallot