pipeline:
  build:
    image: python:3.6
    environment:
      - POSTGRES_USER=timeallot
    commands:
      - sleep 5
      - pip3 install -r requirements/development.txt
      - ./manage.py test
    when:
      event: [push, pull_request] # trigger step on push and pull events


services:
  postgres:
    image: postgres:9.5
    environment:
      - POSTGRES_USER=timeallot