pipeline:
  isort:
    image: python:3.6
    when:
      event: push
    environment:
      - LANG=C.UTF-8
    group: testing
    commands:
      - pip install tox
      - tox -e isort

  flake8:
    image: python:3.6
    when:
      event: push
    environment:
      - LANG=C.UTF-8
    group: testing
    commands:
      - pip install tox
      - tox -e flake8

  yapf:
    image: python:3.6
    when:
      event: push
    environment:
      - LANG=C.UTF-8
    group: testing
    commands:
      - pip install tox
      - tox -e yapf

  ssh:
    image: appleboy/drone-ssh
    host: timeallot.me
    secrets: [ ssh_username, ssh_key ]
    port: 22
    when:
      event: push
    script:
      - ls
      - echo hello
      - echo world


services:
  postgres:
    image: postgres:9.5
    environment:
      - POSTGRES_USER=timeallot