pipeline:
  tests:
    image: python:3.6
    when:
      event: push
    environment:
      - LANG=C.UTF-8
      - DATABASE=postgres
    group: testing
    commands:
      - pip install tox
      - tox -e tests

  ssh:
    image: appleboy/drone-ssh
    host: timeallot.me
    user: sigrid
    secrets: [ ssh_key ]
    port: 22
    script:
      - echo hello
      - echo world


services:
  postgres:
    image: postgres:9.5
    environment:
      - POSTGRES_USER=timeallot