version: '2'

services:
  drone-server:
    image: drone/drone:0.8
    ports:
      - '127.0.0.1:8080:8000'
      - '9000'
    volumes:
      - /var/lib/drone:/var/lib/drone/
    restart: always
    env_file:
      - /etc/drone/dronerc.env

  drone-agent:
    image: drone/agent:0.8

    command: agent
    restart: always
    depends_on:
      - drone-server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DRONE_SERVER=drone-server:9000
    env_file:
      - /etc/drone/dronerc.env