version: '2'

services:

  db:
    restart: always
    image: postgres:9.5
    ports:
      - '127.0.0.1:5432:5432'
    environment:
            POSTGRES_DB: timeallot_db
            POSTGRES_USER: timeallot
            POSTGRES_PASSWORD: password

  nginx:
    depends_on:
      - db
    image: