version: '2'

services:
  db:
    restart: always
    image: postgres:9.5

    environment:
            POSTGRES_USER: timeallot
            POSTGRES_PASSWORD: timeallot
    volumes:
      - ./logs/db:/var/log/postgresql
      - dbdata:/var/lib/postgresql/data

  website:
    restart: always
    build: ./
    volumes:
      - ./:/timeallot
      - ./logs/gunicorn:/gunicorn-logfiles
      - media:/timeallot/public/media
      - static:/timeallot/public/static
    depends_on:
      - db
    env_file: ./timeallot/settings/.env
    ports:
      - "8000:8000"

  proxy:
    build: ./nginx
    ports:
      - "1339:80"
    volumes:
      - static:/timeallot/public/static
      - media:/timeallot/public/media
      - /etc/localtime:/etc/localtime:ro
    links:
      - website:website

  redis:
    image: redis
    ports:
      - '6379:6379'


volumes:
  dbdata:
  media:
  static: