version: '2'

services:

  db:
    restart: always
    image: postgres:9.5
    ports:
      - '127.0.0.1:5490:5432'
    environment:
            POSTGRES_DB: timeallot_db
            POSTGRES_USER: timeallot
            POSTGRES_PASSWORD: timeallot
