# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 20:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeruser',
            name='display_name',
            field=models.TextField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='timeruser',
            name='email',
            field=models.EmailField(
                max_length=254, unique=True, verbose_name='emasil address'),
        ),
    ]
