# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-13 21:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timer', '0002_auto_20171113_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='duration',
            field=models.PositiveSmallIntegerField(default=25),
        ),
        migrations.AlterField(
            model_name='session',
            name='subtags',
            field=models.ManyToManyField(null=True, to='timer.SubTag'),
        ),
    ]
