# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 21:27
from __future__ import unicode_literals

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timer', '0004_auto_20171113_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='starttime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
