# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 21:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timer', '0006_auto_20171114_2139'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='starttime',
            new_name='start_time',
        ),
    ]
