# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 12:15
from __future__ import unicode_literals

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('timer', '0007_auto_20171114_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='projecttag',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='timer.Category'),
        ),
        migrations.AlterField(
            model_name='projecttag',
            name='color',
            field=models.CharField(default='e3e3e3', max_length=10),
        ),
        migrations.AlterField(
            model_name='projecttag',
            name='tag_name',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='timer.ProjectTag'),
        ),
        migrations.AlterField(
            model_name='session',
            name='subtags',
            field=models.ManyToManyField(blank=True, to='timer.SubTag'),
        ),
        migrations.AlterField(
            model_name='subtag',
            name='color',
            field=models.CharField(default='e3e3e3', max_length=10),
        ),
        migrations.AlterField(
            model_name='subtag',
            name='tag_name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
