# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 12:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timer', '0008_auto_20171115_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecttag',
            name='tag_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='subtag',
            name='tag_name',
            field=models.CharField(max_length=30),
        ),
    ]
